import React from 'react';

const Terms = () => {
    return (
        <div style={{ padding: '40px', maxWidth: '900px', margin: '50px auto', backgroundColor: '#1a1a1a', color: '#dfdfdf', borderRadius: '8px', boxShadow: '0 4px 10px rgba(0, 0, 0, 0.2)' }}>
            <h1 style={{ textAlign: 'center', color: '#05923b', marginBottom: '30px' }}>Terms and Conditions</h1>
            <p>
                Welcome to <strong>Medix</strong>, your preliminary medical diagnosis app. By using this application, 
                you agree to comply with the following terms and conditions. Please read them carefully.
            </p>
            
            <section style={{ marginBottom: '20px' }}>
                <h2 style={{ color: '#05923b' }}>1. Purpose</h2>
                <p>
                    <strong>Medix</strong> is designed to assist healthcare professionals by providing preliminary 
                    insights based on patient symptoms. It is not a substitute for official medical diagnosis or treatment.
                </p>
            </section>

            <section style={{ marginBottom: '20px' }}>
                <h2 style={{ color: '#05923b' }}>2. No Medical Advice</h2>
                <p>
                    The information generated by <strong>Medix</strong> is for informational purposes only and should not 
                    be regarded as professional medical advice. Always consult licensed healthcare professionals for 
                    accurate medical guidance and treatment plans.
                </p>
            </section>

            <section style={{ marginBottom: '20px' }}>
                <h2 style={{ color: '#05923b' }}>3. No Warranty</h2>
                <p>
                    We do not guarantee the accuracy, reliability, or completeness of the information provided. Use of this 
                    app is entirely at your own risk. The insights offered by the app are experimental and subject to limitations.
                </p>
            </section>

            <section style={{ marginBottom: '20px' }}>
                <h2 style={{ color: '#05923b' }}>4. Limitation of Liability</h2>
                <p>
                    Medix is not liable for any direct, indirect, incidental, or consequential damages arising from 
                    the use of this app. This includes, but is not limited to, errors in diagnosis or inappropriate 
                    treatment decisions made based on the app's suggestions.
                </p>
            </section>

            <section style={{ marginBottom: '20px' }}>
                <h2 style={{ color: '#05923b' }}>5. User Responsibility</h2>
                <p>
                    By using this app, you acknowledge that it is your responsibility to verify all information and 
                    consult with qualified medical professionals before making any decisions or taking action regarding treatment.
                </p>
            </section>

            <section style={{ marginBottom: '20px' }}>
                <h2 style={{ color: '#05923b' }}>6. Changes to Terms</h2>
                <p>
                    We reserve the right to update these terms and conditions at any time without prior notice. Continued 
                    use of the app indicates acceptance of any modifications made to these terms.
                </p>
            </section>

            <section style={{ marginBottom: '20px' }}>
                <h2 style={{ color: '#05923b' }}>7. Contact Us</h2>
                <p>
                    If you have any questions, concerns, or feedback regarding these terms and conditions, feel free to 
                    reach out to us at <a href="mailto:support@medix.com" style={{ color: '#05923b' }}>support@medix.com</a>.
                </p>
            </section>
        </div>
    );
};

export default Terms;
